### ISSUE TITLE
map.html

### ISSUE THREAD

**Issue by jggunter** [GrayHay/StencilMC#3]
Don't make map.html a redirect. Use a borderless iframe to embed the ugly IP URL on a pretty https.

`
<!DOCTYPE html>
<html>
<head>
	<title>Stencil - Live Map</title>
	<link rel="shortcut icon" href="server-icon.png" type="image/png">
	<style>
		iframe {
			border: none;
			position: fixed;
			top: 0;
			left: 0;
			width: 100%;
			height: 100%;
		}
	</style>
</head>
<body>
	<iframe src="http://209.126.84.212:2071/"></iframe>
</body>
</html>
`

**Comment by GrayHay** [comment]
I have tried this before. The only issue that I experience is that you can not embed an http website into an https website due to security issues. If I were to fix this, I would need backend access to my server, which I have not yet gotten as my host is being slow.

I will definitely update this when I get the chance, it's on my list, but I have more important things to do at the moment.

Thank you!
